spring.application.name=tracenest

spring.datasource.url=jdbc:h2:file:./data/tracenestdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG
